<CFIF findnocase('star',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?Frank-Genius-is-Star-Struck" addtoken="no"></CFIF>
<CFIF findnocase('opus',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?Opus-Spongebobicum" addtoken="no"></CFIF>
<CFIF findnocase('FB03',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?FB03" addtoken="no"></CFIF>
<CFIF findnocase('FB01',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?FB01" addtoken="no"></CFIF>
<CFIF findnocase('FB02',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?FB02" addtoken="no"></CFIF>
<CFIF findnocase('Moers',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?Moers-Works" addtoken="no"></CFIF>
<CFIF findnocase('organs',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?just-3-organs" addtoken="no"></CFIF>
<CFIF findnocase('LAX',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?LAX" addtoken="no"></CFIF>
<CFIF findnocase('Fish',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?Mystery-of-the-Leaping-Fish" addtoken="no"></CFIF>
<CFIF findnocase('ghost',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?Ghost-of-New-York" addtoken="no"></CFIF>
<CFIF findnocase('zahra',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?Zahra-Fugues" addtoken="no"></CFIF>
<CFIF findnocase('fugues',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?Zahra-Fugues" addtoken="no"></CFIF>
<CFIF findnocase('birth',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?Birth-Of-Primary-Cinema-From-The-Spirit-of-Sound" addtoken="no"></CFIF>
<CFIF findnocase('cinema',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?Birth-Of-Primary-Cinema-From-the-Spirit-of-Sound" addtoken="no"></CFIF>
<CFIF findnocase('ameri',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?Amerika" addtoken="no"></CFIF>
<CFIF findnocase('alt',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?ALT" addtoken="no"></CFIF>
<CFIF findnocase('reno',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?RENO" addtoken="no"></CFIF>
<CFIF findnocase('k5',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?K5" addtoken="no"></CFIF>
<CFIF findnocase('radio',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/radio.cfm" addtoken="no"></CFIF>
<CFIF findnocase('school',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?Czerny-School-of-Velocity" addtoken="no"></CFIF>
<CFIF CGI.QUERY_STRING EQ "Cc"><CFLOCATION url="http://rothkamm.com/record.cfm?Czerny-School-of-Velocity" addtoken="no"></CFIF>
<CFIF findnocase('iv',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?FISCH-IV" addtoken="no"></CFIF>
<CFIF findnocase('iii',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?FISCH-III-3+4" addtoken="no"></CFIF>
<CFIF findnocase('killer',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?Killer-Disco" addtoken="no"></CFIF>
<CFIF findnocase('eternal',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?Eternal-Recurrence" addtoken="no"></CFIF>
<CFIF findnocase('wiener',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?wiener-process" addtoken="no"></CFIF>
<CFIF findnocase('reel',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?Commercial-Reel" addtoken="no"></CFIF>
<CFIF findnocase('Beethoven',CGI.QUERY_STRING)><CFLOCATION url="http://rothkamm.com/record.cfm?Beethoven-No.9" addtoken="no"></CFIF>
